# This file was generated by GoReleaser. DO NOT EDIT.
class Datamon < Formula
  desc "A datascience tool to work with data at rest"
  homepage "https://github.com/oneconcern/datamon"
  version "2.0.0-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/oneconcern/datamon/releases/download/v2.0.0-beta/datamon_2.0.0-beta_darwin_amd64.tar.gz"
    sha256 "f44211e1bfe3e756a6aa71a5c9afed5bc506653e594844bdbffa72a17c10ad51"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/oneconcern/datamon/releases/download/v2.0.0-beta/datamon_2.0.0-beta_linux_amd64.tar.gz"
      sha256 "5dbaeed563d448c9e17a514ed71001117f7e1c44e085b205a259beca650839a1"
    end
  end

  def install
    bin.install "datamon"
  end

  test do
    system "#{bin}/datamon", "version"
  end
end
